# Generated by Django 6.0 on 2025-12-31 10:42

import django.db.models.deletion
import djgeoaddress.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("djgeoaddress", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Location name", max_length=255, verbose_name="Name"
                    ),
                ),
                ("address", djgeoaddress.fields.GeoaddressField()),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        help_text="Geoaddress provider",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="djgeoaddress.providermodel",
                        verbose_name="Provider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
                "ordering": ["-created_at"],
            },
        ),
    ]
