# Generated by Django 6.0 on 2025-12-04 14:09

import djgeoaddress.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Location name", max_length=200)),
                (
                    "address",
                    djgeoaddress.fields.AddressField(
                        blank=True,
                        default=dict,
                        help_text="Full address with geocoding",
                        null=True,
                        use_backend=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Test Location",
                "verbose_name_plural": "Test Locations",
                "ordering": ["-created_at"],
            },
        ),
    ]
