# Generated by Django 6.0 on 2025-12-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testlocation",
            name="backend",
            field=models.CharField(
                blank=True,
                help_text="Backend used for geocoding",
                max_length=100,
                null=True,
            ),
        ),
    ]
